#!/usr/bin/env -S guile -s

!#

#|
EVEN FIBONACCI NUMBERS
  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms of the Fibonacci sequence whose values do not exceed four
million, find the sum of the even-valued terms.
|#

(use-modules
  (ice-9 format))

(define (fibseq limit)
  (define (iter a b acc)
    (if (> a limit)
      (reverse acc)
      (if (even? a)
        (iter b (+ a b) (cons a acc))
        (iter b (+ a b) acc))))
  (iter 1 2 '()))

(define (fibsum num)
  (apply + (fibseq num)))

(define result (fibsum 4000000))
(format #t "The sum of fib nums not exceeding 4_000_000 is: ~a" result)
(newline)
