<?php

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

require 'bootstrap.php';

$limit = 4_000_000;
$even_sum = 2;

function fib(int $left, int $right, int $limit, int &$even_sum): void
{
    if ($right >= $limit)
        return;

    $sum = $left + $right;
    $left = $right;
    $right = $sum;

    if ($right % 2 === 0)
        $even_sum += $right;

    fib($left, $right, $limit, $even_sum);
}

fib(1, 2, $limit, $even_sum);

var_dump($even_sum);
